apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "brapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "brapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "brapp.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "brapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.imageTag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: PASSWORD
            - name: THEBIGSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: THEBIGSECRET

          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}

      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
