apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  USERNAME: {{ .Values.secrets.username }}
  PASSWORD: {{ .Values.secrets.password }}
  THEBIGSECRET: {{ .Values.secrets.thebigsecret }}
